const EventEnums = {
    CONNECTION_SUCCESS: "CONNECTION_SUCCESS",
    CONNECTION_ERROR: "CONNECTION_ERROR",
    CONNECTION_CLOSED: "CONNECTION_CLOSED",
    CONNECTION_END: "CONNECTION_END",
    DATA: "DATA",
    MESSAGE: "message"
};

export default {
    EventEnums: EventEnums,
};
